# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
jobs:
  - job: Build
    steps:
      - script: mvn clean install
      - script: mvn package
      - script: ls -ltrh target/*