parameters:
  - name: Username
    type: string
    default: 
  - name: Env
    default: Sandbox
    values:
    - Sandbox
    - Runtime

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package deploy'
    options: '-Dusername=${{ parameters.Username }} -Dpassword=5Vnzur_276332 -Denv=${{ parameters.Env }} -Dworkers=1 -DworkerType=Micro -DmuleDeploy'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/target'
    Contents: '*jar'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'mulesoft'
    publishLocation: 'Container'