# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: client-credential
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: DEVDeployJob
    jobs:
      - deployment: Dev
        environment: dev
        strategy:
         runOnce:
            deploy:
              steps:
                 - script: echo $(ENVIRONMENT.NAME)
                 - script: echo $(ENVIRONMENT.NAME).Username
                 - script: echo ${$(ENVIRONMENT.NAME).Username}