# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildJob
    jobs:
      - job: Build
        steps:
         - task: Maven@3
           inputs:
             mavenPomFile: 'pom.xml'
             publishJUnitResults: false
             javaHomeOption: 'JDKVersion'
             mavenVersionOption: 'Default'
             mavenAuthenticateFeed: false
             effectivePomSkip: false
             sonarQubeRunAnalysis: false
      - job: CopyArtifacts
        steps:
        - task: CopyFiles@2
          inputs:
            Contents: |
              target/*jar
              pom.xml
            TargetFolder: '$(build.artifactstagingdirectory)'

      - job: PublishArtifacts
        steps:
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'mulesoft'
            publishLocation: 'Container'





  - stage: DEVDeployJob
    jobs:
      - deployment: Dev
        environment: dev
        strategy:
         runOnce:
            deploy:
              steps:
              - task: DownloadBuildArtifacts@0
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'mulesoft'
                  downloadPath: '$(System.ArtifactsDirectory)'
              - script: ls -ltrh $(System.ArtifactsDirectory)
              
  - stage: QADeployJob
    jobs:
      - deployment: UAT
        environment: uat
        strategy:
         runOnce:
            deploy:
              steps:
                - script: mvn --version
        
        
         
